// <auto-generated />
namespace ESalesDataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class image_url_string : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(image_url_string));
        
        string IMigrationMetadata.Id
        {
            get { return "202206050803102_image_url_string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
