// <auto-generated />
namespace ESalesDataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class customer_passwordcolumn_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customer_passwordcolumn_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202206071024545_customer_passwordcolumn_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
